# Generated by Django 6.0.6 on 2026-06-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('BOT', 'Trading Bot'), ('AI', 'Trading AI')], max_length=8)),
                ('tier', models.PositiveSmallIntegerField(help_text='Ordering within its kind, 1 = entry level. Used for upgrade comparisons.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('win_chance', models.DecimalField(decimal_places=4, max_digits=5)),
                ('unlocked_contract_count', models.PositiveSmallIntegerField(default=1)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'tier'],
                'unique_together': {('kind', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='UserAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.automationproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'active'], name='bots_userau_user_id_64adb2_idx')],
            },
        ),
    ]
