# Generated by Django 6.0.6 on 2026-06-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='OPEN', max_length=32)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.marketinstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
