# Generated by Django 6.0.6 on 2026-06-26 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('tick_count', models.PositiveBigIntegerField(help_text='Monotonically increasing counter, per instrument.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tick_count'],
            },
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='base_price',
            field=models.DecimalField(decimal_places=6, default=1000, max_digits=18),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='tick_interval_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Milliseconds between ticks for this instrument.'),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='volatility',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text="Standard deviation of each tick's price move, as a percentage (e.g. 0.1 = 0.1%).", max_digits=6),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='contract_type',
            field=models.CharField(choices=[('RISE_FALL', 'Rise/Fall')], default='RISE_FALL', max_length=32),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='duration_unit',
            field=models.CharField(choices=[('ticks', 'Ticks'), ('seconds', 'Seconds')], default='ticks', max_length=10),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='duration_value',
            field=models.PositiveIntegerField(default=5, help_text='Number of ticks, or number of seconds.'),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='entry_tick_count',
            field=models.PositiveIntegerField(blank=True, help_text="For tick-based contracts: the instrument's tick counter value at entry.", null=True),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='For time-based contracts: when this contract settles.', null=True),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='payout_ratio',
            field=models.DecimalField(decimal_places=4, default=0.95, help_text='Payout multiplier on win, e.g. 0.95 = stake back plus 95% profit.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('RISE', 'Rise'), ('FALL', 'Fall')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='tradeposition',
            index=models.Index(fields=['user', 'status'], name='trading_tra_user_id_8f766c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeposition',
            index=models.Index(fields=['instrument', 'status'], name='trading_tra_instrum_94c0e7_idx'),
        ),
        migrations.AddField(
            model_name='tick',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='trading.marketinstrument'),
        ),
        migrations.AddIndex(
            model_name='tick',
            index=models.Index(fields=['instrument', 'tick_count'], name='trading_tic_instrum_67034b_idx'),
        ),
    ]
