# Generated by Django 6.0.6 on 2026-06-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_tradeposition_prediction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('RISE_FALL', 'Rise/Fall'), ('EVEN_ODD', 'Even/Odd'), ('HIGHER_LOWER', 'Higher/Lower'), ('OVER_UNDER', 'Over/Under'), ('MATCHES_DIFFERS', 'Matches/Differs'), ('TOUCH_NO_TOUCH', 'Touch/No Touch')], max_length=32)),
                ('side', models.CharField(blank=True, max_length=8)),
                ('prediction', models.JSONField(blank=True, default=dict)),
                ('duration_unit', models.CharField(choices=[('ticks', 'Ticks'), ('seconds', 'Seconds')], max_length=10)),
                ('duration_value', models.PositiveIntegerField()),
                ('stake', models.DecimalField(decimal_places=2, max_digits=18)),
                ('stop_loss', models.DecimalField(decimal_places=2, help_text='Stop automatically once cumulative loss reaches this amount.', max_digits=18)),
                ('take_profit', models.DecimalField(decimal_places=2, help_text='Stop automatically once cumulative profit reaches this amount.', max_digits=18)),
                ('cumulative_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trades_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED_MANUAL', 'Stopped by user'), ('STOPPED_STOP_LOSS', 'Stopped — stop-loss hit'), ('STOPPED_TAKE_PROFIT', 'Stopped — take-profit hit'), ('STOPPED_INSUFFICIENT_FUNDS', 'Stopped — insufficient funds')], default='RUNNING', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trading.tradeposition')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.marketinstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='trading_bot_user_id_8b98ad_idx')],
            },
        ),
    ]
